### ISSUE TITLE
error: Failed: The specified format is not supported or cannot be translated.

### ISSUE THREAD

**Issue by drencorxeen** [MyTDT-Mysoft/COCO-FastLoader#2]
Downloaded the current binaries and was trying to use in Windows 10 64bit command prompt:

I tried to do a:
FastLoad.exe -p -w spores.bin
and got
![image](https://user-images.githubusercontent.com/14010507/103402229-d9785000-4b11-11eb-8325-81fbe7027969.png)
Is there any easy workaround for this or will I have to dig around for some older hardware and OS to run this on?

**Comment by MyTDT-Mysoft** [comment]
hum... yeah i think quickly fix that and commit an update, i think i already had it fixed a long time ago, but it was not commited (or binaries updated)

**Comment by MyTDT-Mysoft** [comment]
done commited... and updated win32 binaries :)

**Comment by drencorxeen** [comment]
Ooo it works :)
What FreeBASIC options did you use to rebuild it so it worked, cause I tried to build the sources myself and still got the same issue?

**Comment by MyTDT-Mysoft** [comment]
well you need to get the source again, since i commited the changes on
snd-w32-mmsystem.bas to fix that issue.

Em qui., 31 de dez. de 2020 às 17:47, David Ladd <notifications@github.com>
escreveu:

**Comment by drencorxeen** [comment]
Ah cool :)
I missed that

I have been tinkering with cassette port stuff on the CoCo the last few weeks tinkering with just messing with the basic load timings to try to get 2X mode and on a CoCo 3 in double speed mode loading a normal WAV file in 4X :)
I had been wanting to tinker with this, but thankfully with the WAV output option I can pre-setup the WAV files and then just use a normal player later at any time. :)

I have been using Audacity as my WAV player so far on Windows.

**Comment by MyTDT-Mysoft** [comment]
yeah the only issue is that for small files it would worth to keep the
binary loaded on coco so it wouldnt need to load that loader over and over
again, but oh well... without a cart that is not possible hehe

Em qui., 31 de dez. de 2020 às 18:44, David Ladd <notifications@github.com>
escreveu:

**Comment by drencorxeen** [comment]
Oh also noticed another thing when building I have to rename the inc folder to MyTDT for it to build?
Not sure if your fastloader.bas has a different folder in it compared to the repo?

**Comment by MyTDT-Mysoft** [comment]
oh, i will check because maybe its finding the file on the inc folder of my
freebasic (instead of the project one)

Em qui., 31 de dez. de 2020 às 19:43, David Ladd <notifications@github.com>
escreveu:

**Comment by drencorxeen** [comment]
Just thought I would let you know either way. :)  Just in case.

**Comment by drencorxeen** [comment]
Oh also noticed another thing when building I have to rename the inc folder to MyTDT for it to build?
Not sure if your fastloader.bas has a different folder in it compared to the repo?

**Comment by drencorxeen** [comment]
Ok updated my comparison video
Here is updated link:
https://youtu.be/offwBh5QXoU

**Comment by MyTDT-Mysoft** [comment]
cool :)

Em dom., 3 de jan. de 2021 às 21:18, David Ladd <notifications@github.com>
escreveu:

**Comment by drencorxeen** [comment]
Second video I made using Marble Maze as that is a 29K binary and figured that would be a good comparison :)
https://youtu.be/A30qi-7WNps

**Comment by drencorxeen** [comment]
I also noticed there is a Modules and modules folders.  To build the current code I had to manually move the code from the modules folder to the Modules folder to get the updated file.

Just thought I would let you know about this.

**Comment by MyTDT-Mysoft** [comment]
heh funny i have to check that... as obviously i only have a single folder,
but that is because on windows the case is irrelevant, but so i wonder how
you ended with two folders hehe

Em ter., 12 de jan. de 2021 às 00:15, David Ladd <notifications@github.com>
escreveu:

**Comment by drencorxeen** [comment]
Well that is because I for the most part run Linux OS's and thus is case sensitive :D lol

Once I got the required packages installed and FreeBASIC I was able to build the project. :)

Sadly still having issues getting it to run on the Raspberry Pi 3 and Raspberry Pi 4. :O

**Comment by MyTDT-Mysoft** [comment]
hehehe yes, but directories are not created out of thin air... so what
created different folders? :P

Em qua., 13 de jan. de 2021 às 16:35, David Ladd <notifications@github.com>
escreveu:

**Comment by drencorxeen** [comment]
It was probably the git command where you had to add the source file back into the project you might have done a 
git add modules/Snd-w32-mmsystem.bas
rather than a
git add Modules/Snd-w32-mmsystem.bas

Cause git will respect the case sensitive OS's which is why it created a second directory in the repo lol

**Comment by MyTDT-Mysoft** [comment]
yeah ok, you are probably right, i have not noticed that, and downloading
the repo and unzipping (on windows) obviously didnt showed the problem
either hehe

Em qua., 13 de jan. de 2021 às 17:34, David Ladd <notifications@github.com>
escreveu:
